/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PM_Converter_param_t */

#ifndef _Included_PM_Converter_param_t
#define _Included_PM_Converter_param_t
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
