/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PM_Converter */

#ifndef _Included_PM_Converter
#define _Included_PM_Converter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PM_Converter
 * Method:    PM_create_J
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_PM_1Converter_PM_1create_1J
  (JNIEnv *, jobject);

/*
 * Class:     PM_Converter
 * Method:    PM_destroy_J
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_PM_1Converter_PM_1destroy_1J
  (JNIEnv *, jobject);

/*
 * Class:     PM_Converter
 * Method:    PM_manage_J
 * Signature: (Ljava/lang/String;CI)I
 */
JNIEXPORT jint JNICALL Java_PM_1Converter_PM_1manage_1J
  (JNIEnv *, jobject, jstring, jchar, jint);

/*
 * Class:     PM_Converter
 * Method:    PM_parseFrom_J
 * Signature: (Ljava/lang/String;C)I
 */
JNIEXPORT jint JNICALL Java_PM_1Converter_PM_1parseFrom_1J
  (JNIEnv *, jobject, jstring, jchar);

/*
 * Class:     PM_Converter
 * Method:    PM_hasValue_J
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_PM_1Converter_PM_1hasValue_1J
  (JNIEnv *, jobject, jstring);

/*
 * Class:     PM_Converter
 * Method:    PM_getValue_J
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_PM_1Converter_PM_1getValue_1J
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
