/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PM_Converter */

#ifndef _Included_PM_Converter
#define _Included_PM_Converter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PM_Converter
 * Method:    PM_create_J
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_PM_1Converter_PM_1create_1J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     PM_Converter
 * Method:    PM_destroy_J
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_PM_1Converter_PM_1destroy_1J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     PM_Converter
 * Method:    PM_manage_J
 * Signature: (Ljava/lang/String;CIJ)I
 */
JNIEXPORT jint JNICALL Java_PM_1Converter_PM_1manage_1J
  (JNIEnv *, jobject, jstring, jchar, jint, jlong);

/*
 * Class:     PM_Converter
 * Method:    PM_parseFrom_J
 * Signature: (Ljava/lang/String;CJ)I
 */
JNIEXPORT jint JNICALL Java_PM_1Converter_PM_1parseFrom_1J
  (JNIEnv *, jobject, jstring, jchar, jlong);

/*
 * Class:     PM_Converter
 * Method:    PM_hasValue_J
 * Signature: (Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_PM_1Converter_PM_1hasValue_1J
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     PM_Converter
 * Method:    PM_getValue_J
 * Signature: (Ljava/lang/String;J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_PM_1Converter_PM_1getValue_1J
  (JNIEnv *, jobject, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
